### ISSUE TITLE
Should be able to set Curl timeout for requests

### ISSUE THREAD

**Issue by sebarobaze** [TourCMS/tourcms-php#3]
In `TourCMS\Utils\TourCMS::request()`, `CURLOPT_TIMEOUT` is set to 0, which means the request will hang forever if unable to connect to the API.

This should have a sensible default and be a public property, so that it can be modified.

**Comment by paulslugocki** [comment]
Agreed!

**Comment by zaidapalisis** [comment]
Hi sebarobaze,
It is already fixed in v3.0.7 that just went up
